# Generated by Django 3.2.7 on 2021-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('cweight', models.FloatField()),
                ('dweight', models.FloatField()),
                ('height', models.FloatField()),
                ('birthday', models.DateField()),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('dateofjoining', models.DateField()),
                ('trainer', models.CharField(max_length=200)),
                ('gymbefore', models.CharField(max_length=200)),
                ('membership', models.CharField(max_length=200)),
            ],
        ),
    ]
