# Generated by Django 3.2.7 on 2021-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='username',
            field=models.CharField(default='darshu', max_length=200),
        ),
    ]
