# Generated by Django 3.2.7 on 2021-11-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userdetail_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='rpassword',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
