# Generated by Django 3.2.7 on 2022-01-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userlogin_rpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('Pic', models.FileField(upload_to='')),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('JoinDate', models.DateField()),
                ('BirthDate', models.DateField()),
            ],
        ),
    ]
