# Generated by Django 3.2.7 on 2022-01-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='Status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
