# Generated by Django 3.2.7 on 2022-01-07 18:49

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20220107_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='Pic',
            field=models.ImageField(upload_to=login.models.filepath),
        ),
    ]
