# Generated by Django 3.2.7 on 2022-01-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_trainer_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageName', models.CharField(max_length=200)),
                ('Pic', models.ImageField(upload_to='static/css/pictures')),
                ('Price', models.IntegerField()),
                ('Details', models.CharField(max_length=200)),
            ],
        ),
    ]
