# Generated by Django 3.2.7 on 2022-01-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('Pic', models.ImageField(upload_to='pictures')),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
