# Generated by Django 3.2.7 on 2022-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_batches_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='batches',
            name='BatchTiming',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diet',
            name='Time',
            field=models.CharField(max_length=100),
        ),
    ]
