# Generated by Django 3.2.7 on 2022-01-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220127_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MealName', models.CharField(max_length=200)),
                ('Pic', models.ImageField(upload_to='pictures')),
                ('Recipe', models.CharField(max_length=200)),
            ],
        ),
    ]
